apiVersion: serving.knative.dev/v1alpha1
kind: Route
metadata:
  name: spring-java
spec:
  traffic:
  - configurationName: spring-java
    percent: 100
---
apiVersion: serving.knative.dev/v1alpha1
kind: Configuration
metadata:
  name: spring-java
spec:
  build:
    # Run this build as our build-bot
    serviceAccountName: build-bot
    source:
      git:
        url: https://github.com/srinivasa-vasu/spring-music.git
        revision: master
    template:
      name: buildpack
      arguments:
      - name: IMAGE
        value: <username>/spring-java
      env:
      - name: PACK_APP_ZIP
        value: spring-music-0.1.jar
  revisionTemplate:
    metadata:
      labels:
        knative.dev/type: spring-music
    spec:
      container:
        image: <username>/spring-java